title: page.title.product

options:
  changeSlug: false
  changeTemplate: false
  delete: false

fields:
  price:
    extends: fields/price
  tax:
    label: field.tax
    type: number
    required: true
    step: 1
    min: 0
    max: 100
    after: %
